server:
  port: 80
  servlet:
    contest-path: /

spring:
  application:
    name: springboot-redis
  redis:
    host: 127.0.0.1
    port: 6379
    username:
    password:
    #哨兵
    sentinel:
      master: master
      password:
      #哨兵节点
      nodes: 127.0.0.1:26379,127.0.0.1:26380
    #lettuce连接池
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 32
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 300
        # 连接池中的最大空闲连接
        max-idle: 16
        # 连接池中的最小空闲连接
        min-idle: 8
      database:
    connect-timeout: 10000

