server:
  port: 80
  servlet:
    contest-path: /
  tomcat:
    threads:
      max: 200
    uri-encoding: UTF-8

spring:
  application:
    name: springboot-thymeleaf
  thymeleaf:
    prefix:
      classpath: /template
    suffix: .html
    encoding: UTF-8
    cache: false
    mode: HTML5
